import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarMenu } from "@/components/Sidebar";
import NavbarComponent from "@/components/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <div className="grid grid-cols-[auto,1fr]">
        <div className="">
            <SidebarMenu />
        </div>
        <div className="flex flex-col px-6 py-4">
            <NavbarComponent />
            <main className="w-full p-4">{children}</main>
        </div>
    </div>
      </body>
    </html>
  );
}
